server:
  port: ${SERVER_PORT:8080}

spring:

  application:
    name: ${APP_NAME:spring-boot-demo}

  config:
    import:
      - optional:classpath:application-common.yaml

app:
  slogan: ${APP_SLOGAN:!!!}
