server:
  port: ${SERVER_PORT:80}

spring:
  application:
    name: ${APP_NAME:spring-boot-demo}

  threads:
    virtual:
      enabled: true

springdoc:
  group-configs:
    - group: default
      paths-to-match: /api/**
