name: Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      DOCKER_HUB_NAMESPACE: daodaobot
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      APP_NAME: spring-boot-demo
      APP_VERSION: 0.0.1

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn spring-boot:build-image -Pnative

      - name: Login Docker Hub
        run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

      - name: Tag the Docker image
        run: docker tag $APP_NAME:$APP_VERSION $DOCKER_HUB_NAMESPACE/$APP_NAME:latest

      - name: Push the Docker Image
        run: docker push $DOCKER_HUB_NAMESPACE/$APP_NAME:latest
