name: Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml -U -Pnative spring-boot:build-image

    - name: Login Docker Hub
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

    - name: Tag the Docker image
      run: docker tag spring-boot-demo:0.0.1 daodaobot/spring-boot-demo:latest

    - name: Push the Docker Image
      run: docker push daodaobot/spring-boot-demo:latest
